minio:
  endpoint: http://192.168.233.202:9000
  bucket: llp
  accessKey: admin
  secretKey: admin123

spring:
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小
