spring:
  datasource:
    url: jdbc:mysql://localhost:3306/llp?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.79.202
    port: 6379
    #Redis 数据库索引（默认为 0）
    database: 0
    #连接超时时间（毫秒）
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #连接池中的最大空闲连接
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8888
