server:
  port: 8888

#\u914D\u7F6Emybatis
mybatis-plus:
  configuration:
    #\u5F00\u542F\u4E0B\u5212\u7EBF\u6620\u5C04\u9A7C\u5CF0\u547D\u540D
    map-underscore-to-camel-case: true
    #mybatis\u65E5\u5FD7\u6253\u5370
    # xml\u6587\u4EF6\u4F4D\u7F6E\u6620\u5C04
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/llp?autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: root
