server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
# 配置SQL分析打印
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatisplus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    url: jdbc:p6spy:mysql://localhost:3306/mybatisplus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
    #针对Date类型时间,格式化处理
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8

############## Mybatisplus多数据源配置 ##############
#spring:
#  datasource:
#    dynamic:
#      primary: master #设置默认的数据源或者数据源组,默认值即为master
#      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#      datasource:
#        master:
##          url: jdbc:mysql://localhost:3306/mybatisplus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          url: jdbc:p6spy:mysql://localhost:3306/mybatisplus?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: root
#          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
##          driver-class-name: com.mysql.jdbc.Driver
#        slave_1:
#          url: jdbc:mysql://localhost:3306/mp2?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: root
#          driver-class-name: com.mysql.jdbc.Driver
#        slave_2:
#          url: jdbc:mysql://localhost:3306/mp3?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
#          username: root
#          password: root
#          driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  #方式一： 3.5.2以前配置通用枚举包扫描，3.5.2以后只需要声明注解即可
  #typeEnumsPackage: com.llp.mybatisplus.constant
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  #方式二：3.5.2以前配置通用枚举直接指定 DefaultEnumTypeHandler
    #default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤，只需在实体中标注@TableLogic注解即可)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

